### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by Baristi000** [phamdinhkhanh/general_ocr#4]
### Setup:

<img width="1660" alt="Screen Shot 2021-10-17 at 1 17 03 AM" src="https://user-images.githubusercontent.com/54427194/137598008-960cd056-bd94-4483-a011-800b5ee2f056.png">

### Log ERROR:
```log
Traceback (most recent call last):
  File "general_ocr/utils/ocr.py", line 7, in <module>
    import general_ocr
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/__init__.py", line 10, in <module>
    from .apis import *
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/apis/__init__.py", line 2, in <module>
    from .inference import init_detector, model_inference, inference_detector
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/apis/inference.py", line 10, in <module>
    from general_ocr.core import get_classes
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/core/__init__.py", line 4, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/core/bbox/samplers/__init__.py", line 10, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from general_ocr.ops import nms_match
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('general_ocr.' + name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python3.7/dist-packages/general_ocr-0.0.1-py3.7.egg/general_ocr/_ext.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by phamdinhkhanh** [comment]
You shouldn't install general_ocr package on colab notebook because on colab notebook it is harder to create and manage your conda virtual environment.

In case you are running google colab, we provide you a starting colab notebook guideline:
https://colab.research.google.com/drive/15vEit2dsumS-c_m_RB6T5cxU7KkYZOKU?usp=sharing
